### ISSUE TITLE
Criar Wiki

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#1]
# Issue Template

## Descrição da Issue
Para podermos deixar de forma organizada a nossa documentação, atas e afins, é necessário criar uma wiki que possibilite um bom aspecto visual e boa organização dos artefatos produzidos.

### Tasks:
- [x] Cria Wiki (Docussaurus/MKDocs)
- [x] Configurar Wiki
- [x] Construir Home Page do Time
- [x] Configurar o Deploy Contínuo dos documentos a serem inserido em Markdown

## Assignees
@rogerioo 
@MarcosNBJ 
@DanilloGS

**Comment by rogerioo** [comment]
Issue concluída com sucesso e wiki disponível no [link](https://fga-projeto-integrador-1.github.io/Projeto/). A medida que o projeto for avançando, o index vai sendo atualizado.

**Comment by rogerioo** [comment]
Aguardando review do @DanilloGS .
