### ISSUE TITLE
Definição e Aquisição dos Materiais Estruturais

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#14]
## Descrição da Issue
Definir os materiais a serem utilizados na confecção dos artigos de bancada (viga, pesos, apoio, estrutura externa), pesquisar o melhor custo-benefício de materiais, o local onde estão disponíveis e documentar tudo o que for adquirido.

### Tasks:
- [x] Definir os materiais à serem utilizados para a bancada (#9)
- [x] Definir o material da viga a partir de cálculos de deformação (#10)
- [ ] Criar um orçamento (#11)
- [x] Concluir design da bancada (#12)
- [x] Documentação (#13)
- [ ] Compra de materiais da estrutura (#46)

## Assignees
A issue deve ser atribuída a pelo menos um colaborador do projeto.

**Comment by rogerioo** [comment]
Sprint finalizadas e dividas técnicas realocadas para a próxima sprint.
