### ISSUE TITLE
Circuito e Dados para alimentação da câmera

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#16]
## Descrição da Issue
Documentar consumo de energia de cada componente do circuito da câmera e definir fonte alimentação.

### Tasks:
- [x] Fazer uma planilha de consumo de energia
- [x] Fazer documento sobre a fonte de alimentação
- [x] Fazer Relatório de Atividade

### Critérios de aceitação:
- [x] Planilha de consumo de Energia. 
- [x] Documentação

## Assignees
@haackmarcella 
@matheusgvieira

**Comment by haackmarcella** [comment]
Eu estou fazendo a pesquisa sobre o consumo de energia e o levantamento de uso da bancada ao longo do semestre e a analise da fonte de alimentacao mais viavel para os componentes. Logo mais estarei postando os resultados

**Comment by matheusgvieira** [comment]
### Andamento da Atividade

A @haackmarcella e @matheusgvieira, discutiram sobre ornamentação das fitas de led, baseado no CAD elaborado pela equipe de Estrutura. Foi definido **posições** e **quantidade** de fitas de led. Logo, as informações estarão na documentação que será entregue no decorrer no dia.

**Comment by haackmarcella** [comment]
Planilha de consumo de energia e pesquisa sobre fontes de alimentação viáveis e relatório de atividades. 
[Pesquisa - Consumo de energia e fonte de alimentação  .docx](https://github.com/ssol-organization/Wiki/files/3192468/Pesquisa.-.Consumo.de.energia.e.fonte.de.alimentacao.docx)
[Relatório de atividades -  Consumo de energia e fonte de alimentação  .docx](https://github.com/ssol-organization/Wiki/files/3192469/Relatorio.de.atividades.-.Consumo.de.energia.e.fonte.de.alimentacao.docx)

**Comment by rogerioo** [comment]
Pesquisa bem embasada e explicação bem feita. Muito bom!
