### ISSUE TITLE
Definição e Aquisição de Componentes Eletrônicos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#20]
## Descrição da Issue
Definir os componentes a serem utilizados no sistema da câmera e iluminação (câmera, raspberry, tripé, luzes, outros), pesquisar o melhor custo-benefício dos componentes, o local onde estão disponíveis e documentar tudo o que for adquirido.

### Tasks:
- [x] Pesquisa e diagrama de microcontroladores e iluminação (#45)
- [ ] Simulação dos componentes definidos (#15)
- [ ] Circuito e Dados para alimentação da câmera (#16)
- [ ] Fechar orçamento (#17)
- [ ] Adquirir materiais (#18)
- [ ] Documentação (#19)

## Assignees
@matheusgvieira 
@Vkaio 
@iaraandrade 
@haackmarcella

**Comment by matheusgvieira** [comment]
## Feedback da @iaraandrade  sobre a atividade:
Foi tranquilo, a única coisa que pesou é o tempo curto em uma semana lotada, de resto foi tudo certo

**Comment by matheusgvieira** [comment]
### Feedback do @Vkaio sobre a atividade:
Não fiquei com dúvidas, inclusive acredito q o melhor componente para a câmera será o Módulo ESP32-CAM

**Comment by rogerioo** [comment]
Sprint finalizada e dividas técnicas realocadas para próxima sprint.
