### ISSUE TITLE
Definição das Tecnologias e Metodologias de Software

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#26]
## Descrição da Issue
Definir as tecnologias para programação(ambientes dockerizados, linguagens de programação, ambientes de deploy, ambiente de testes, ambientes de homologação, estrutura de micro serviços, aplicativo) e técnicas de visão computacional (metodologias de extração das informação da bancada por meio da imagem capturada) à serem utilizadas.

### Tasks:
- [x] Definir tecnologias (#21)
- [x] Definir arquitetura do sistema (#22)
- [x] Definir os ambientes (#23)
- [x] Definir técnicas de visão computacional (#24)
- [x] Definir pontos restantes de visão de produto inicial para o aplicativo (#44 )
- [x] Documentação (#25)

**Comment by rogerioo** [comment]
Todas as atividades realizadas foram realizadas e estão disponíveis na Wiki do projeto, com exceção do layout do aplicativo que está disponível no [link](https://marvelapp.com/5107fie).
