### ISSUE TITLE
Confecção dos esquemas e diagramas dos componentes eletrônicos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#29]
## Descrição da Issue
Diagramar o fluxo de dados, desde solicitação da imagem ao microcontrolador até o recebimento no servidor, assim como, o uso da iluminação da caixa. Usar o draw.io.

### Tasks:
- [x] Diagrama em PDF
- [x] Documentação 

### Critérios
- [x] Documentação bem formatada.
- [x] Pelo menos 2 comentários na Issue

## Assignees
@haackmarcella 
@iaraandrade

**Comment by matheusgvieira** [comment]
### Atualização da Atividade
Já está sendo realizado, a demora é devido o entendimento do funcionamento da câmera e iluminação, assim como, o uso do draw.io.

**Comment by matheusgvieira** [comment]
## Diagramas
![Coleta_Imagem](https://user-images.githubusercontent.com/47388740/58046403-91aedb80-7b1b-11e9-9a99-8aaf1824385b.jpeg)
![WhatsApp Image 2019-05-20 at 16 13 45](https://user-images.githubusercontent.com/47388740/58046404-91aedb80-7b1b-11e9-91be-94d7e039f0ad.jpeg)

**Comment by iaraandrade** [comment]
[Relatório de Atividades - Diagramas .pdf](https://github.com/ssol-organization/Wiki/files/3210002/Relatorio.de.Atividades.-.Diagramas.pdf)

**Comment by rogerioo** [comment]
Tudo certinho!
