### ISSUE TITLE
Documentação de eletrônica da sprint 03

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#30]
## Descrição da Issue
Fazer uma documentação completa de todas atividades da Issue #31 

### Tasks:
- [x] Documentação em PDF

### Critérios
- [x] Documentação bem formatada
- [x] Pelo menos 2 comentários na Issue

## Assignees
@matheusgvieira 
@haackmarcella 
@Vkaio 
@iaraandrade

**Comment by matheusgvieira** [comment]
### Atualização da Atividade
Estamos levantando todos os dados, para a construção da documentação da issue.

**Comment by matheusgvieira** [comment]
### Relatório da Sprint3
Como ainda falta uma issue, o documento está sujeito a alterações, mas até aqui é isso que temos:
[sprint3.pdf](https://github.com/ssol-organization/Wiki/files/3198490/sprint3.pdf)

**Comment by rogerioo** [comment]
O resto da documentação está disponível [aqui](#29)
