### ISSUE TITLE
Esquemático e Montagem dos Componentes Eletrônicos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#31]
## Descrição da Issue
Montar o esquema do circuito da câmera com o módulo ESP32-CAM e o circuito de iluminação. Realizar primeiro teste com envio de imagem para o servidor. Definir a instalação da iluminação. Confeccionar o CAD da câmera.

### Tasks:
- [x] Simulação dos componentes definidos (#15)
- [x] Circuito e Dados para alimentação da câmera (#16)
- [x] Fechar orçamento (#17)
- [x] Confeccionar esquemas e diagramas do sistema (#29)
- [x] Documentação (#30)

### Critérios
- [ ] Documentação bem formatada em todas atividades
- [x] Pelo menos 2 comentários na Issue

## Assignees
@matheusgvieira 
@haackmarcella 
@Vkaio 
@iaraandrade

**Comment by matheusgvieira** [comment]
## ATA DA REUNIÃO REALIZADA DIA 18/05 ÀS 10 HRS
[ATA_18_05_2019_Projeto_PI1_Eletronica.pdf](https://github.com/ssol-organization/Wiki/files/3194161/ATA_18_05_2019_Projeto_PI1_Eletronica.pdf)

**Comment by matheusgvieira** [comment]
### Atualização da Issue

Estamos a todo vapor para a finalização da sprint, esperamos que até 16 horas do dia 20 de Maio, esteja tudo finalizado.
