### ISSUE TITLE
Definição dos Materiais de Bancada e Orçamento

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#36]
## Descrição da Issue
Aperfeiçoar o CAD da bancada com o pontos que ficaram faltando. Definir as medidas dos materiais (viga, pesos, apoios) para poder fechar orçamento. Definir a graduação da viga com as cores e posições pré-determinadas. Definir os apoios, os tipos de peso, forças distribuídas, como os pesos serão visualmente e como serão fixos na viga.

### Tasks:
- [x] Pesquisa de materiais alternativos para a viga (#53)
- [x] Finalizar o dimensionamento da viga (#33)
- [x] Finalizar o dimensionamento dos pesos (#51)
- [ ] Finalizar o dimensionamento dos apoios (#52)
- [x] Finalizar o esquema em CAD de toda a bancada (#32)
- [ ] Fechar orçamento de materiais (#34)
- [x] Documentação (#35)

## Assignees
@DaniloFernandesDuarte 
@matalencar 
@LucasGlopes 
@jaosvgarcia 
@MonteiroC
