### ISSUE TITLE
Definir proposta de Solução

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#4]
# Issue Template

## Descrição da Issue
De acordo com o que foi acordado entre o grupo e com o professor, definir o proposta de solução do projeto.

### Tasks:
- [ ] Pesquisar o que compoẽ a proposta de solução necessária ao Ponto de Controle I
- [ ] Encontrar modelo à ser seguido
- [ ] Definir proposta de solução
- [ ] Confeccionar artefato

## Assignees
@matalencar 
@Vkaio

**Comment by rogerioo** [comment]
Issue atendida pelo [documento](https://drive.google.com/open?id=1jqauqhYCoeA4TehHNRD49vpWm_9TSDj3) disponível no drive.
