### ISSUE TITLE
Criar Primeira Versão do Sistema

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#43]
## Descrição da Issue
Criar primeira interface do aplicativo. Começar a implementação dos algoritmos de visão computacional definidos anteriormente. Criação dos ambientes de desenvolvimento dos microsserviços. Começar a implementação do microsserviço de geração de diagramas. Implementação primeira versão arquitetural de todo o backend.

### Tasks:
- [x] Confeccionar o diagrama arquitetural do sistema e fluxo de dados (#37)
- [x] Criar primeira versão do aplicativo (#38)
- [x] Criação dos ambientes de desenvolvimento de microsserviços (#42  )
- [x] Começar a desenvolver o microsserviço ImageProcessAPI (#39)
- [x] Começar a desenvolver o microsseviço Calculus API(#54 )
- [x] Relatório das atividades realizadas (#41)

## Assignees
@MarcosNBJ 
@DanilloGS 
@joao15victor08 
@pedroeagle 
@rogerioo

**Comment by rogerioo** [comment]
Todas as issue foram entregues pelo grupo e o desenvolvimento e o resultado está registrado nas mesma.
