### ISSUE TITLE
Pesquisa sobre Microcontroladores e Iluminação

### ISSUE THREAD

**Issue by matheusgvieira** [fga-projeto-integrador-1/Projeto#45]
## Descrição da Issue
Fazer uma pesquisa sobre componente para a iluminação e controle do sistema da câmera, detalhando sobre cada componente, seguindo os comandos postados no slack.

### Tasks:
- [x] Pesquisa dos Microcontroladores
- [x] Pesquisa do Circuito de Iluminação
- [x] Definição de Componentes para Simulação
- [x] Fazer Relatório de Atividade

## Assignees
@Vkaio 
@iaraandrade 
@haackmarcella 
@matheusgvieira

**Comment by matheusgvieira** [comment]
Pesquisa de Microcontroladores:

[PESQUISA_MICROCONTROLADORES.pdf](https://github.com/fga-projeto-integrador-1/Projeto/files/3147947/PESQUISA_MICROCONTROLADORES.pdf)

**Comment by matheusgvieira** [comment]
Pesquisa do Circuito de Iluminação:

[Fita de LEDs.pdf](https://github.com/fga-projeto-integrador-1/Projeto/files/3149307/Fita.de.LEDs.pdf)

**Comment by matheusgvieira** [comment]
## Relatório de Issue
[RELATÓRIO ISSUE 45.pdf](https://github.com/fga-projeto-integrador-1/SSol/files/3164219/RELATORIO.ISSUE.45.pdf)

**Comment by rogerioo** [comment]
Tarefa concluída com sucesso.
