### ISSUE TITLE
Compra de materiais da estrutura

### ISSUE THREAD

**Issue by DaniloFernandesDuarte** [fga-projeto-integrador-1/Projeto#46]
# Compra de materiais

### Tasks:
- [ ] Criar lista de compras 
- [ ] Encontrar fornecedores viáveis 
- [ ] Iniciar as compras

**Comment by DaniloFernandesDuarte** [comment]
A lista de compras está em andamento. O orçamento e finalização do design ocorrerão antes que essa etapa tome andamento
