### ISSUE TITLE
Definir fundamentação teórica do Projeto

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#6]
# Issue Template

## Descrição da Issue
Como o escopo do projeto está dentro de MecSol I e vai usar conceitos de Visão Computacional, é necessário definir o embasamento teórico daquilo que será produzido pelo grupo.

### Tasks:
- [ ] Falar com o professor Glauco para saber sua opinião com relação à viabilidade das ideias do grupo para o projeto
- [x] Encontrar modelo à ser seguido
- [x] Definir embasamento teórico
- [x] Confeccionar artefato

## Assignees
@MonteiroC 
@pedroeagle 
@DaniloFernandesDuarte

**Comment by pedroeagle** [comment]
Tudo isso deve ser escrito em um único documento? Qual o formato e diretório deve ser colocado?

**Comment by pedroeagle** [comment]
Grande parte do conteúdo escrito foi feito no drive, sendo este o motivo de poucos commits e atraso no cumprimento da tarefa. Sobre a conversa com o Glauco, não foi possível encontrá-lo na semana passada por conta dos feriados e por ele ter cancelado uma aula. A conversa será feita na quarta-feira.
