### ISSUE TITLE
Colocar ambientes em produção e Realizar Testes

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#60]
# Descrição da Issue
Colocar os ambientes desenvolvidos na sprint anterior em produção (Image Process, Calculus e o APP). Modularizar o código do Image Process API. Realizar testes simulados da bancada (barra, pesos e apoios) com uma distância mínima. Adicionar funcionalidade no aplicativo que permita renderizar imagens a partir de URL e organizar o layout. 

## Tasks:
- [x] Modularizar o código do Image Process API
- [x] Colocar ambiente do Image Process API em produção
- [ ] Colocar ambiente do Calculus API em produção
- [ ] Adição da nova funcionalidade ao APP e organização do layout
- [ ] Colocar ambiente do APP em produção

# Assignees
@MarcosNBJ 
@rogerioo 
@DanilloGS 
@pedroeagle 
@joao15victor08
