### ISSUE TITLE
Teste de envio de imagens a partir da ESP

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#62]
# Descrição da Issue
Teste com as funcionalidades da câmera de acordo com os requisitos do projeto, visando adiantar atividades antes da chegada da câmera.

## Tasks:
- [x] Desenvolver código de envio de imagens.
- [x] Desenvolver código de armazenamento de imagem no cartão SD.
- [x] Relatório de Atividade.

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@Vkaio

**Comment by matheusgvieira** [comment]
### Relatório de Armazenamento de Dados no SD
[Relatório de Atividade - SDCard.pdf](https://github.com/ssol-organization/Wiki/files/3224836/Relatorio.de.Atividade.-.SDCard.pdf)

**Comment by matheusgvieira** [comment]
### Atualização da Issue
Estamos progredindo, porém houve dificuldades com a pinagem da esp, que dificultaram a execução da atividade, é previsto ao longo do da 28 de Maio a finalização da issue.

**Comment by matheusgvieira** [comment]
### Atualização da Atividade
Estamos conseguindo realizar algumas detalhes no código, porém deparamos com limitações, por causa da falta do hardware, mas como o componente já chegou, vamos acelerar o processo.

**Comment by Vkaio** [comment]
O código já foi desenvolvido, no entanto o módulo conversor USB para TTL tá estragado, tentei criar um novo, pois não temos tempo para comprar outro, mas não deu certo. Agora, usaremos a ESP32S do Matheus G. para arrumar esse problema

**Comment by Vkaio** [comment]
![image](https://user-images.githubusercontent.com/28969347/59231321-a3cde800-8bb6-11e9-97b2-6481e871f127.png)

**Comment by Vkaio** [comment]
[Relatório de Atividade - ESP32CAM.pdf](https://github.com/ssol-organization/Wiki/files/3288417/Relatorio.de.Atividade.-.ESP32CAM.pdf)
[Cod_HTML.txt](https://github.com/ssol-organization/Wiki/files/3288418/Cod_HTML.txt)
![hjk](https://user-images.githubusercontent.com/28969347/59473649-b98f1780-8e19-11e9-8391-a9198a6d1fe0.jpg)
