### ISSUE TITLE
Testes e Aquisição dos Componentes Eletrônicos

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#66]
# Descrição da Issue
CAD do sistema da câmera. Teste de envio de imagens. Definir o suporte da câmera. Testes de iluminação. Definição do terminal de energia. Aquisição dos componentes eletrônicos e documentação.  

## Tasks:
- [x] Confecção do CAD do sistema da câmera (#61)
- [ ] Teste de envio de imagens a partir da ESP (#62)
- [x] Definição do suporte da câmera (#63)
- [x] Testes de iluminação simulando a bancada (#64)
- [x] Definição do terminal de energia (#65)
- [x] Desenvolvimento do terminal de alimentação (#68)
- [ ] Sistema com WebCam e Raspberry (#69)
- [x] Documentação dos componentes adquiridos

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@matheusgvieira 
@iaraandrade 
@haackmarcella 
@Vkaio

**Comment by matheusgvieira** [comment]
### Esclarecimento sobre atividade
***Aquisição dos componente eletrônicos*** e ***Documentação dos componentes adquiridos*** não terão issue individuais, com isso, essas atividades serão postadas aqui na issue #66

**Comment by matheusgvieira** [comment]
### Lista de Componentes
[Planilha Final - Eletrônica - Página1.pdf](https://github.com/ssol-organization/Wiki/files/3221756/Planilha.Final.-.Eletronica.-.Pagina1.pdf)

Porém ainda está sujeita a modificações, visto que alguns membros já possui alguns componentes e é previsto o adicionamento de equipamento para auxilia na organização dos fios do circuito de iluminação.

**Comment by matheusgvieira** [comment]
### Atualização de Issue
Estamos progredindo nas atividades, porém o atraso delas é devido a impasses de comunicação e alinhamento entre as áreas.

**Comment by matheusgvieira** [comment]
### Atualização de Issue
Amanhã vou organizar tudo o que foi realizado em um só documento, de acordo com a Gerente Amanda pediu.
