### ISSUE TITLE
Finalizar dimensionamentos e orçamento

### ISSUE THREAD

**Issue by rogerioo** [fga-projeto-integrador-1/Projeto#67]
# Descrição da Issue
Dimensionamento e CAD dos apoios. Dimensionamento e CAD dos pesos. Finalizar o orçamento.

## Tasks:
- [ ] Dimensionamento dos apoios
- [ ] CAD dos apoios
- [ ] Dimensionamento dos pesos
- [ ] CAD dos pesos
- [ ] Fechar orçamento definitivo

# Assignees
@DaniloFernandesDuarte 
@jaosvgarcia 
@matalencar 
@LucasGlopes 
@MonteiroC

**Comment by MonteiroC** [comment]
Os CAD's dos pesos não foram fechados ainda por conta que temos que saber qual o tamanho mínimo que o QR CODE  pode ter (eu acho que isso só poderá ser definido quando a câmera estiver conosco, não sei exatamente, se eu estiver errado me corrijam). Sobre isso tomamos como base, que nossos pesos serão retangulares, de área de secção transversal com no mínimo 8mm² ao máximo de 10mm², podendo haver alteração na medida mínima.
Nossos pesos serão de material compensado, semelhante ao que levei na reunião de quarta-feira, com preenchimento de massa de cimento, ou areia, ou chumbo. E as massas estipuladas para eles são de 1kg, 2kg e 4kg.

**Comment by MonteiroC** [comment]
Estou vendo a melhor possibilidade para os pesos triangulares, mas em questão de material será o mesmo dos pesos retangulares.
