### ISSUE TITLE
Desenvolvimento do terminal de alimentação

### ISSUE THREAD

**Issue by matheusgvieira** [fga-projeto-integrador-1/Projeto#68]
# Descrição da Issue
Montar o circuito do terminal no fritzing e na protoboard e fazer integração com as fitas de leds.

## Tasks:
- [x] Foto do esquemático montado em protoboard.
- [x] Fazer esquemático no Fritzing.
- [x] Diagrama de funcionamento.
- [x] Relátorio de Atividade

## Critérios de Aceitação:
- 2 comentários da issue.
- Documentação bem formatada.
- Esquemático no Fritzing.

# Assignees
@haackmarcella 
@iaraandrade

**Comment by matheusgvieira** [comment]
## Atualização da Atividade
Ontem fizemos testes e conseguimos traçar e realizar a lógica de operação prevista. A atividades está bem encaminhada. Decidimos utilizar uma PCB, como suporte e interligação dos componentes. Ainda há indefinições com o PLUG P4 da fonte e uma fonte adequada para o sistema, mas estamos correndo atrás disso.

**Comment by matheusgvieira** [comment]
### Esquemático no Fritzing
[esquematico_fritzing.zip](https://github.com/ssol-organization/Wiki/files/3266115/esquematico_fritzing.zip)

**Comment by haackmarcella** [comment]
## Diagrama de funcionamento do circuito 
[Diagrama Circuito Eletronico.pdf](https://github.com/ssol-organization/Wiki/files/3269648/Diagrama.Circuito.Eletronico.pdf)

**Comment by haackmarcella** [comment]
## Relatório de Atividades 
[Relatório de Atividade - Circuito Eletrônico.pdf](https://github.com/ssol-organization/Wiki/files/3269654/Relatorio.de.Atividade.-.Circuito.Eletronico.pdf)

**Comment by matheusgvieira** [comment]
## Finalização da Issue
Todas as taks foram concluídas com sucesso, amanhã executaremos o terminal em definitivo, incluindo a soldagem dos componentes na PCB. O único impasse é quantidade de fitas de led, que talvez não dê, mas estamos nos organizando pra resolver isso.
