### ISSUE TITLE
Sistema com WebCam e Raspberry

### ISSUE THREAD

**Issue by matheusgvieira** [fga-projeto-integrador-1/Projeto#69]
# Descrição da Issue
Devido ao atraso e complicações com o pedido da Esp32-CAM será realizado paralelamente, um sistema reserva caso o pedido da câmera não ocorra como planejado. Deverá ser feito uma integração da raspberry com uma Go-Pro, e mandar informações gráficas para o servidor.

## Tasks:
- [ ] Integração Go-Pro com Raspberry.
- [ ] Conectar via API com o servidor
- [ ] Relatório de Atividade

## Critérios de Aceitação:
- Documentação.
- No mínimo dois comentários da issue.

# Assignees
@matheusgvieira 
@Vkaio

**Comment by matheusgvieira** [comment]
## Atualização da Atividade
Estou com algumas dificuldades com a gopro, mas já fiz pesquisas e já comecei a mexer na raspberry, a atividade está bem encaminhada, espero terminar até sábado, se conseguir superar as dificuldades com a GoPro

**Comment by matheusgvieira** [comment]
## Atualização da Atividade
Essa atividade está com problemas com a gopro. Mesmo com a chegada da Esp32, esta atividade ocorrerá paralelamente, caso as funções da Esp32 não estejam funcionando corretamente. **A atividade será o plano B.**

**Comment by matheusgvieira** [comment]
## Finalização de Atividade
Devido ao sucesso com os testes da esp32-cam foi decidido fechar essa Issue, pois ela dependia do bom funcionamento na esp32-cam.
