### ISSUE TITLE
Integração dos Sistemas Eletrônicos e Estruturais

### ISSUE THREAD

**Issue by matheusgvieira** [fga-projeto-integrador-1/Projeto#70]
# Descrição da Issue
Integrar o sistema de iluminação, em conjunto com os sistema da câmera, na caixa e viga. Encaixe do terminal no local previamente determinado e conexões internas.

## Tasks:
- [ ] Integração da Câmera
- [ ] Integração da Iluminação
- [ ] Integração do Terminal de Energia e demais sistemas.

## Critérios de aceitação
- Documentação das atividades

# Assignees
@Vkaio 
@matheusgvieira 
@haackmarcella 
@iaraandrade 
@amandahenriques

**Comment by matheusgvieira** [comment]
# Informações sobre a issue
Galera de eletrônica, como estamos com todas as partes individuais funcionando, então entramos em fase final, de integração. Vou separa-los dessa maneira:

* **Amanda e Marcella** => Integração com iluminação (Instalação das Fitas de Led)
* **VK** => Integração com a Cãmera (Cola com a galera de software de preferência o Pedro Igor e Marcoszão)
* **Matheus e Iara** => Integração do Terminal (Finalização, soldagem e fiação).

**Comment by matheusgvieira** [comment]
# Teste com Iluminação
![20190612_183845](https://user-images.githubusercontent.com/47388740/59438007-01d21980-8dc9-11e9-8468-5116d5c9f750.jpg)
![20190612_183906](https://user-images.githubusercontent.com/47388740/59438009-026ab000-8dc9-11e9-9bf1-aae993271721.jpg)

**Comment by matheusgvieira** [comment]
## Terminal de Energia
Temos que revisar o circuito do terminal, em questão do consumo de corrente de cada componente, e distribuir adequadamente para o seu bom funcionamento.

**Comment by matheusgvieira** [comment]
## Câmera
Não conseguimos fazer o teste com a câmera, devido ao desenvolvimento da pintura e demais atividade na estrutura. Até semana que vem esperamos terminar essa atividade de integração com todo o sistema.

**Comment by matheusgvieira** [comment]
## Testes com a Câmera
![1](https://user-images.githubusercontent.com/47388740/59651883-ecab1100-9161-11e9-870c-8392a1d05108.jpeg)
![3](https://user-images.githubusercontent.com/47388740/59651885-ecab1100-9161-11e9-954a-838ce5410138.jpeg)

**Comment by matheusgvieira** [comment]
## Atualização da Issue

**Integração Iluminação **
Já foi decido o local e já foi feito o testes com a imagem, devido ao sucesso da atividade, o que resta é instalação final para a apresentação. Já foi dado inicio as atividades de instalação.

**Integração com a Câmera**
Testes de imagem tiradas com a câmera foram realizadas com êxito, a dependência agora é com a conectividade com o servidor. Caso se torne um problema, alocaremos todos os membros de eletrônica para a atividade, visando a finalização da atividade, que possuí uma complexidade alta.

**Terminal de Energia**
A parte de conectividade com as fitas de led está ok, o que falta agora é consertar a iteração com o microcontrolador (Câmera). Estamos com dificuldade devido distribuição de corrente no terminal.

**Comment by matheusgvieira** [comment]
## Atualização da Issue

**Integração Iluminação**
Já foi decido o local e já foi feito o testes com a imagem, devido ao sucesso da atividade, o que resta é instalação final para a apresentação. Já foi dado inicio as atividades de instalação.

**Integração com a Câmera**
Testes de imagem tiradas com a câmera foram realizadas com êxito, a dependência agora é com a conectividade com o servidor. Caso se torne um problema, alocaremos todos os membros de eletrônica para a atividade, visando a finalização da atividade, que possuí uma complexidade alta.

**Terminal de Energia**
A parte de conectividade com as fitas de led está ok, o que falta agora é consertar a iteração com o microcontrolador (Câmera). Estamos com dificuldade devido distribuição de corrente no terminal.
